# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Node dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy build via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./public/build/
          target: /home/clients/55e169f47915a898f04c35eb6533338a/sites/dondusang.loannjuillerat.ch/public/

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_ed25519
            cd /home/clients/55e169f47915a898f04c35eb6533338a/sites/dondusang.loannjuillerat.ch
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache